services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672", "15672:15672"]
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.5
    command: start-single-node --insecure --store=/cockroach/cockroach-data
    ports: ["26257:26257", "8080:8080"]
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  # ---------- STORAGE NODE ----------
  node1:
    build: ./backend/storage_node
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      REDIS_URL: redis://redis:6379/0
      CACHE_TTL: "300"
      COCKROACH_URL: cockroachdb://root@cockroachdb:26257/defaultdb?sslmode=disable
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_started
      cockroachdb:
        condition: service_started

  # ---------- WORKER ----------
  worker:
    build: ./backend/storage_node
    command: ["python", "worker.py"]
    environment:
      REDIS_URL: redis://redis:6379/0
      CACHE_TTL: "300"
      COCKROACH_URL: cockroachdb://root@cockroachdb:26257/defaultdb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_NAME: kv_requests
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      cockroachdb:
        condition: service_started

  # ---------- NGINX LOAD BALANCER ----------
  nginx:
    build:
      context: ./backend/nginx
    ports:
      - "80:80"
    depends_on:
      - envoy
    networks:
      - default

  # ---------- ENVOY PROXY ----------
  envoy:
    build:
      context: ./backend/envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:8080"
      - "9901:9901"
    depends_on:
      - node1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/server_info"]
      interval: 10s
      retries: 3

  # ---------- API GATEWAY ----------
  gateway:
    build: ./backend/api_gateway
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      NODE_URL: http://envoy:8080
    expose:
      - "8000"
    depends_on:
      node1:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  cockroach-data:
  redis-data:
  rabbit-data: