services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.5
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data:/cockroach-data

  node1:
    build:
      context: ./backend/storage_node
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL=300
      - COCKROACH_URL=cockroachdb://root@cockroachdb:26257/defaultdb?sslmode=disable
    ports:
      - "8100:8000"
    volumes:
      - ./storage_data:/data
    depends_on:
      - redis
      - cockroachdb

  gateway:
    build:
      context: ./backend/api_gateway
      dockerfile: Dockerfile
    environment:
      - NODE_URL=http://node1:8000
    ports:
      - "8000:8000"
    depends_on:
      - node1

volumes:
  cockroach-data: